on: 
    - push 

jobs:
    smoke-test:
        runs-on: ubuntu-latest
        steps:
            - name: set up the Ocaml toolchain
              run: |
                sudo apt-get install bubblewrap
                echo "" | bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
                yes | opam init